version: 2

defaults: &defaults
  working_directory: ~/app

py_defaults: &py_defaults
  <<: *defaults
  docker:
  - image: python:3.6.3

docker_defaults: &docker_defaults
  <<: *defaults
  machine: true

jobs:
  lint:
    <<: *py_defaults
    steps:
    - checkout
    - run: |
        pip install -r requirements.txt
        ./lint.sh
  unit_test:
    <<: *py_defaults
    steps:
    - checkout
    - run: |
        pip install -r requirements.txt
        ./test.sh
  build:
    <<: *docker_defaults
    steps:
    - checkout
    - run: ./build.sh

workflows:
  version: 2
  continuous_integration:
    jobs:
    - lint
    - unit_test
    - build:
        requires:
        - lint
        - unit_test
